export default {
  WIDGETS_CHANGE: 'WIDGETS_CHANGE',
  SET_PAGE: 'SET_PAGE',
  SET_WIDGETS: 'SET_WIDGETS',
  SET_DEPENDENCIES: 'SET_DEPENDENCIES',
  CLEAR_WIDGETS: 'CLEAR_WIDGETS',
  INITIALIZE: 'INITIALIZE',
  GET_WIDGETS: 'GET_WIDGETS',
  SET_GRID: 'SET_GRID',
  SET_WIDGET_PROPS: 'SET_WIDGET_PROPS'
}